{
    "name": "Motel Booking",
    "version": "17.0.1.0.1",
    "summary": "Booking module for motel management",
    "category": "Hospitality",
    "author": "Your Name",
    "license": "LGPL-3",
    "depends": [
        "motel_base",
        "motel_security",
        "motel_room",
        "motel_guest",
        "motel_service",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/motel_booking_views.xml",
        "views/motel_room_kanban_inherit.xml",
        "views/motel_booking_menus.xml",
    ],
    "application": False,
    "installable": True,
}
