[options]
admin_passwd = $pbkdf2-sha512$600000$FAIgBOA8JyTEWAvhHCNk7A$n9xohfoQnrO1EL1xjkO2wZGZjOe0nHDDqfrO4cn3YH.PmzmwNRkO4i/Lq0FTTj9nRA1NGDQ7kqLgnZUY1fk4rw
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
proxy_mode = True
log_level = info
workers = 0
max_cron_threads = 1
